_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 53
                - 71
            "3":
                - 13
                - 16
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": linux-aarch64
batch_size:
    value: 8
d_ff:
    value: 256
d_model:
    value: 256
data_root:
    value: /home/ubuntu/hcy50662/output_mimic3
devices:
    value: "0"
dropout:
    value: 0.1
e_layers:
    value: 2
ehr_task:
    value: pheno
exp_name:
    value: pheno_d256_h4_l2_lr5e-05
factor:
    value: 1
gpu:
    value: 0
huggingface_token:
    value: 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
learning_rate:
    value: 5e-05
llm_model_path:
    value: meta-llama/Meta-Llama-3-8B-Instruct
max_seq_len:
    value: 4000
n_heads:
    value: 4
num_class:
    value: 24
patch_len:
    value: 4
seq_len:
    value: 24
stride:
    value: 2
train_epochs:
    value: 500
use_gpu:
    value: true
use_multi_gpu:
    value: false
use_wandb:
    value: true
wandb_project:
    value: MM-TSFlib-EHR
